### ISSUE TITLE
Provide the means to limit functionality to "daylight" hours

### ISSUE THREAD

**Issue by lagerratrobe** [MazamaScience/MazamaSatelliteUtils#44]
Update package functionality  so that only files during Daytime hours are downloaded/processed.

**Comment by jonathancallahan** [comment]
Thinking about this issue, I currently have the following use case in mind:

* A fire pops up in the Sierras and can be seen in the monitors and the smoke forecast models.
* A user wants to see what the satellite AOD shows for that region over the course of a day -- quick `rasterVis::levelplot()` with each level an hourly average of available data.
* User only has a laptop with limited memory and doesn't want to wait forever.

We have a few lego bricks in place for this functionality provided `goesaodc_downloadAOD()` has a function signature that includes the following parameters:

```
  satID = NULL,
  datetime = NULL,
  timezone = "UTC",
  bbox = c(-125, -65, 24, 50), # CONUS
  fullDay = FALSE,
  julian = FALSE, # Suggestion
  daylightOnly = TRUE,
```

I imagine the most common use case will be someone specifying the date time naturally. They see a spike in smoke at 3pm local time and they want to specify something like:

```
  ...
  datetime = "2019-10-09 15:00"
  timezone = "America/Los_Angeles"
  ...
```

or `datetime = 2019100915` or just `datetime = 20191009` for a full day.

I'm pretty sure we need to force people to specify the `timezone` parameter because determining it from the `box` may cause problems if `bbox` is large.

Also, I don't think there is any need to support a separate `jdate`. But, if we want to support julian timestamps, we could add the suggested `julian` flag.

With all this information and our existing lego bricks:

* `bboxToVector()` -- in utils.R
* `isDaylight()` -- in utils-time.R
* `goesaodc_listFiles()`

we should be able to refactor this function to do this following:

```
# ----- Validate parameters
# ----- Convert time information to UTC POSIXct
(# ----- Find daylight hours for the period and bbox of interest) ??Or does listFiles take care of this??
# ----- Determine files to download
  something like setdiff( listRemoteFiles(...), listLocalFiles(...))
# ----- Download needed files
```

**Comment by lagerratrobe** [comment]
I like this idea, but I don't think the Download function should keep track of the fullDay logic.  It should just download files using times and satellite info as arguments.  Instead, let's wrap this logic into another low-level function called "getDaylightHours".  We can then write a "high-level" function (if we have to), downloadDaylightAOD() that wraps these inside of it.

Proposed user workflow and function logic/signature:

```
# MINIMUM INPUT PARAMETERS
satID = "G16"
datetime = "2019-10-09 15:00"
timezone = "America/Los_Angeles"

# ------------------------------------------------------- #

# LOW-LEVEL DAYTIME FILE DOWNLOAD SCENARIO
day_hours <- getDaylightHours(
          datetime = "2019-10-09 15:00"
           timezone = "America/Los_Angeles")

sunrise <- day_hours$sunrise  # POSIXt return
sunset <- day_hours$sunset    # POSIXt return

goesaodc_downloadAOD(
          datetime = sunrise, 
          endTime = sunset, 
          satID = satID)
# ------------------------------------------------------- #

# HIGH-LEVEL DAYTIME FILE DOWNLOAD 
day_files <- goesaodc_downloadDaylightAOD(
          satID = satID, 
          datetime = datetime, 
          timezone = timezone)

# ------------------------------------------------------- #

# LOW-LEVEL RASTER STACK FOR A DAY
day_hours <- getDaylightHours(
          datetime = "2019-10-09 15:00"
           timezone = "America/Los_Angeles")

sunrise <- day_hours$sunrise  # POSIXt
sunset <- day_hours$sunset    # POSIXt

goesaodc_createRasterSatck(
          satID = satID, 
          datetime = sunrise, 
          endTime = sunset, 
          dqfLevel = 2)

# ------------------------------------------------------- #

# HIGH-LEVEL RASTERSTACK FOR A DAY

goesaodc_createDaytimeRasterStack(
          satID = satID,
          datetime = datetime,
          timezone = timezone,
          dqfLevel = 2)

```
__NOTE__: One thing to pay special attention to is that return values from getDaylightHours() will be in the same timezone as what you pass in.  If you don't specify one, UTC will be assumed, which is the default behavior across the package now.

<ins>Questions for Jon:</ins>
1. What means of defining daylight boundaries do you want?
* timezone
* bbox
* lat/lon point
* ?????
2. Does this concept work for you?

**Comment by lagerratrobe** [comment]
Added new goesaodc_getDaylightHours() function and tests to package.
